[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-submit-sitemap"
  
 
    [plugins.inputs]
    buildDir = "public"
    # The base url of your site (optional, default = main URL set in Netlify)
    baseUrl = "https://rawcacaobliss.netlify.app/"
 
    # Path to the sitemap URL (optional, default = /sitemap.xml)
    sitemapPath = "/sitemap.xml"
 
    # Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
    providers = [
        "google",
        "bing",
        "yandex"
    ]
    [[plugins]]
  package = "netlify-plugin-submit-sitemap"
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    buildDir = "public"
    ]
